# Read the Docs configuration file.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
    nodejs: "16"
  jobs:
    post_create_environment:
      # Use NPM, since yarn isn't available by default.
      - 'npm install'
      # Run the preprocessing script.
      - 'node -r ts-node/register documentation/scripts/readthedocs_preprocess.ts'

mkdocs:
  configuration: mkdocs.yml

python:
   install:
   - requirements: requirements.txt
