// Typedoc settings.
// See: https://typedoc.org/options/
module.exports = {
  name: 'Pack SDK Reference',
  excludeExternals: true,
  excludePrivate: true,
  excludeProtected: true,
  excludeInternal: true,
  plugin: [
    'typedoc-plugin-markdown',
    'typedoc-plugin-frontmatter',
    './documentation/scripts/typedoc_plugin.mjs',
  ],
  // Don't include the repo's README in the generated docs.
  readme: 'documentation/reference/README.md',

  // NOTE(patrick): I'm not sure why this is necessary, but without it, we saw a strange
  // resolution of PackVersionDefinition links being resolved as PackDefinition links in
  // the generated docs.
  useTsLinkResolution: false,

  // Markdown-specific options.
  hideBreadcrumbs: true,
  entryFileName: 'index',
  hidePageHeader: true,
  typeDeclarationFormat: 'table',
  parametersFormat: 'table',
  blockTagsPreserveOrder: ['@example', '@deprecated'],
  pageTitleTemplates: {
    // Generate a page title for a module like "Module: Core" instead of "core".
    module: args => `Module: ${args.name.slice(0, 1).toUpperCase()}${args.name.slice(1)}`,
  },
  // Don't generate an separate page for the module listing.
  mergeReadme: true,

  // Frontmatter-specific options.
  // Additional dynamic frontmatter is set in typedoc_plugin.mjs.
  frontmatterGlobals: {
    note: `
This file is autogenerated from TypeScript definitions. Make edits to the comments in the TypeScript file and then
run "make docs" to regenerate this file.
    `.trim(),
    search: {
      boost: 0.1,
    },
  },

  intentionallyNotExported: [
    // Internal intermediate or helper types that we probably don't care to export or document.
    '$Values',
    'AsAuthDef',
    'AutocompleteParameterTypeMapping',
    'AutocompleteParameterTypes',
    'BaseInvocationError',
    'BooleanHintValueTypes',
    'Exact',
    'NumberHintValueTypes',
    'OptionsReference',
    'ObjectHintValueTypes',
    'ObjectSchemaDefinitionType',
    'ObjectSchemaType',
    'ParameterTypeMap',
    'SimpleStringHintTypes',
    'StringHintTypeToSchemaType',
    'StringHintValueTypes',
    'TypeMap',
    'TypeOf',
    'TypeOfMap',
    'UnionType',

    // Internal only types.
    'AllowedAuthentication',
    'AllowedAuthenticationDef',
    'CategorizationIndexDefinition',
    'CodaInternalRichTextSchema',
    'GuideScreenAnnotation',

    // In development.
    'DetailedIndexedProperty',
    'GlobalKnowledgeToolSource',

    // Deprecated features we should remove from the SDK.
    'FeatureSet',
    'PackCategory',
    'Quota',
    'RateLimits',
  ],
};
