blank_issues_enabled: false
contact_links:
  - name: Superhuman Packs SDK support
    url: https://docs.superhuman.com/packs/build/latest/support/
    about: Please ask and answer all questions here rather than opening issues in this repo.
