blank_issues_enabled: false
contact_links:
  - name: Coda Packs SDK support
    url: https://coda.io/packs/build/latest/support/
    about: Please ask and answer all questions here rather than opening issues in this repo.
