/* eslint-disable */
/**
 * @file TypeScript SDK for Coda API. This file is autogenerated from the API's OpenAPI specification,
 * available at https://coda.io/developers/apis/v1
 *
 * Version: v1
 * Hash: 3cb65a92b168c432b6eb8cad28cd0cc16911c3536d86f2d256c7ddb6007de8ad
 */

import 'es6-promise/auto';
import 'cross-fetch/polyfill';
import {withQueryParams} from '../url';
import * as types from './v1';

export class ResponseError extends Error {
  response: Response;

  constructor(response: Response) {
    super(response.statusText);
    this.response = response;
  }
}

export function isResponseError(err: any): err is ResponseError {
  return err instanceof ResponseError;
}

export class Client {
  private readonly protocolAndHost: string;
  private readonly apiToken: string;
  private readonly userAgent: string;

  constructor({
    apiToken,
    protocolAndHost = 'https://coda.io',
    userAgent = 'Coda-Typescript-API-Client',
  }: {
    apiToken: string;
    protocolAndHost?: string;
    userAgent?: string;
  }) {
    this.protocolAndHost = protocolAndHost;
    this.apiToken = apiToken;
    this.userAgent = userAgent;
  }

  private async _makeRequest<T>(method: string, url: string, body?: string): Promise<T> {
    const response = await fetch(url, {
      headers: {
        Authorization: `Bearer ${this.apiToken}`,
        'Content-Type': 'application/json',
        'User-Agent': this.userAgent,
      },
      method,
      body,
    });
    if (response.status >= 400) {
      throw new ResponseError(response);
    }
    return response.json();
  }

  async listCategories(params: {} = {}): Promise<types.PublicApiDocCategoryList> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/categories`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async listDocs(
    params: {
      isOwner?: boolean;
      isPublished?: boolean;
      query?: string;
      sourceDoc?: string;
      isStarred?: boolean;
      inGallery?: boolean;
      workspaceId?: string;
      folderId?: string;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiDocList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/docs`, pageToken ? {pageToken} : rest);
    return this._makeRequest('GET', codaUrl);
  }

  async createDoc(params: {} = {}, payload: types.PublicApiDocCreate): Promise<types.PublicApiDoc> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/docs`, allParams);
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async getDocsCount(
    params: {
      isPublished?: boolean;
      isOwner?: boolean;
      workspaceId?: string;
    } = {},
  ): Promise<types.PublicApiCountResponse> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/docs/count`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async getDoc(docId: string, params: {} = {}): Promise<types.PublicApiDoc> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/docs/${docId}`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async deleteDoc(docId: string, params: {} = {}): Promise<types.PublicApiDocDelete> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/docs/${docId}`, allParams);
    return this._makeRequest('DELETE', codaUrl);
  }

  async getSharingMetadata(docId: string, params: {} = {}): Promise<types.PublicApiAcl> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/docs/${docId}/acl/metadata`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async getPermissions(docId: string, params: {} = {}): Promise<types.PublicApiAcl> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/docs/${docId}/acl/permissions`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async addPermission(
    docId: string,
    params: {} = {},
    payload: types.PublicApiAddPermissionRequest,
  ): Promise<types.PublicApiAddPermissionResult> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/docs/${docId}/acl/permissions`, allParams);
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async deletePermission(
    docId: string,
    permissionId: string,
    params: {} = {},
  ): Promise<types.PublicApiDeletePermissionResult> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/acl/permissions/${permissionId}`,
      allParams,
    );
    return this._makeRequest('DELETE', codaUrl);
  }

  async publishDoc(
    docId: string,
    params: {} = {},
    payload: types.PublicApiDocPublish,
  ): Promise<types.PublicApiPublishResult> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/docs/${docId}/publish`, allParams);
    return this._makeRequest('PUT', codaUrl, JSON.stringify(payload));
  }

  async unpublishDoc(docId: string, params: {} = {}): Promise<types.PublicApiUnpublishResult> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/docs/${docId}/publish`, allParams);
    return this._makeRequest('DELETE', codaUrl);
  }

  async listPages(
    docId: string,
    params: {
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiPageList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/pages`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async getPage(docId: string, pageIdOrName: string, params: {} = {}): Promise<types.PublicApiPage> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/docs/${docId}/pages/${pageIdOrName}`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async updatePage(
    docId: string,
    pageIdOrName: string,
    params: {} = {},
    payload: types.PublicApiPageUpdate,
  ): Promise<types.PublicApiPageUpdateResult> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/docs/${docId}/pages/${pageIdOrName}`, allParams);
    return this._makeRequest('PUT', codaUrl, JSON.stringify(payload));
  }

  async listTables(
    docId: string,
    params: {
      sortBy?: types.PublicApiSortBy;
      tableTypes?: string;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiTableList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/tables`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async getTable(
    docId: string,
    tableIdOrName: string,
    params: {
      useUpdatedTableLayouts?: boolean;
    } = {},
  ): Promise<types.PublicApiTable> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/docs/${docId}/tables/${tableIdOrName}`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async listColumns(
    docId: string,
    tableIdOrName: string,
    params: {
      visibleOnly?: boolean;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiColumnList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/tables/${tableIdOrName}/columns`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async listRows(
    docId: string,
    tableIdOrName: string,
    params: {
      query?: string;
      sortBy?: types.PublicApiRowsSortBy;
      useColumnNames?: boolean;
      valueFormat?: types.PublicApiValueFormat;
      visibleOnly?: boolean;
      syncToken?: string;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiRowList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/tables/${tableIdOrName}/rows`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async upsertRows(
    docId: string,
    tableIdOrName: string,
    params: {
      disableParsing?: boolean;
    } = {},
    payload: types.PublicApiRowsUpsert,
  ): Promise<types.PublicApiRowsUpsertResult> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/tables/${tableIdOrName}/rows`,
      allParams,
    );
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async deleteRows(
    docId: string,
    tableIdOrName: string,
    params: {} = {},
    payload: types.PublicApiRowsDelete,
  ): Promise<types.PublicApiRowsDeleteResult> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/tables/${tableIdOrName}/rows`,
      allParams,
    );
    return this._makeRequest('DELETE', codaUrl, JSON.stringify(payload));
  }

  async getRow(
    docId: string,
    tableIdOrName: string,
    rowIdOrName: string,
    params: {
      useColumnNames?: boolean;
      valueFormat?: types.PublicApiValueFormat;
    } = {},
  ): Promise<types.PublicApiRowDetail> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/tables/${tableIdOrName}/rows/${rowIdOrName}`,
      allParams,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async updateRow(
    docId: string,
    tableIdOrName: string,
    rowIdOrName: string,
    params: {
      disableParsing?: boolean;
    } = {},
    payload: types.PublicApiRowUpdate,
  ): Promise<types.PublicApiRowUpdateResult> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/tables/${tableIdOrName}/rows/${rowIdOrName}`,
      allParams,
    );
    return this._makeRequest('PUT', codaUrl, JSON.stringify(payload));
  }

  async deleteRow(
    docId: string,
    tableIdOrName: string,
    rowIdOrName: string,
    params: {} = {},
  ): Promise<types.PublicApiRowDeleteResult> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/tables/${tableIdOrName}/rows/${rowIdOrName}`,
      allParams,
    );
    return this._makeRequest('DELETE', codaUrl);
  }

  async pushButton(
    docId: string,
    tableIdOrName: string,
    rowIdOrName: string,
    columnIdOrName: string,
    params: {} = {},
  ): Promise<types.PublicApiPushButtonResult> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/tables/${tableIdOrName}/rows/${rowIdOrName}/buttons/${columnIdOrName}`,
      allParams,
    );
    return this._makeRequest('POST', codaUrl);
  }

  async getColumn(
    docId: string,
    tableIdOrName: string,
    columnIdOrName: string,
    params: {} = {},
  ): Promise<types.PublicApiColumnDetail> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/tables/${tableIdOrName}/columns/${columnIdOrName}`,
      allParams,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async listFormulas(
    docId: string,
    params: {
      sortBy?: types.PublicApiSortBy;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiFormulaList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/formulas`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async getFormula(docId: string, formulaIdOrName: string, params: {} = {}): Promise<types.PublicApiFormula> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/formulas/${formulaIdOrName}`,
      allParams,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async listControls(
    docId: string,
    params: {
      sortBy?: types.PublicApiSortBy;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiControlList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/controls`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async getControl(docId: string, controlIdOrName: string, params: {} = {}): Promise<types.PublicApiControl> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/controls/${controlIdOrName}`,
      allParams,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async whoami(params: {} = {}): Promise<types.PublicApiUser> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/whoami`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async resolveBrowserLink(
    url: string,
    params: {
      degradeGracefully?: boolean;
    } = {},
  ): Promise<types.PublicApiApiLink> {
    const allParams = {
      ...params,
      url,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/resolveBrowserLink`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async getMutationStatus(requestId: string, params: {} = {}): Promise<types.PublicApiMutationStatus> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/mutationStatus/${requestId}`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async triggerWebhookAutomation(
    docId: string,
    ruleId: string,
    params: {} = {},
    payload: types.PublicApiWebhookTriggerPayload,
  ): Promise<types.PublicApiWebhookTriggerResult> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/docs/${docId}/hooks/automation/${ruleId}`,
      allParams,
    );
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async listDocAnalytics(
    params: {
      isPublished?: boolean;
      sinceDate?: string;
      untilDate?: string;
      scale?: types.PublicApiAnalyticsScale;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiDocAnalyticsCollection> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/analytics/docs`, pageToken ? {pageToken} : rest);
    return this._makeRequest('GET', codaUrl);
  }

  async listDocAnalyticsDeprecated(
    params: {
      isPublished?: boolean;
      sinceDate?: string;
      untilDate?: string;
      scale?: types.PublicApiAnalyticsScale;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiDeprecatedDocAnalyticsCollection> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/analytics/docs/legacy`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async listDocAnalyticsSummary(
    params: {
      isPublished?: boolean;
      sinceDate?: string;
      untilDate?: string;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiDocAnalyticsSummary> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/analytics/docs/summary`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async listPackAnalytics(
    params: {
      packIds?: string;
      workspaceId?: string;
      sinceDate?: string;
      untilDate?: string;
      scale?: types.PublicApiAnalyticsScale;
      orderBy?: types.PublicApiPackAnalyticsOrderBy;
      direction?: types.PublicApiSortDirection;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiPackAnalyticsCollection> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/analytics/packs`, pageToken ? {pageToken} : rest);
    return this._makeRequest('GET', codaUrl);
  }

  async listPackAnalyticsSummary(
    params: {
      packIds?: string;
      workspaceId?: string;
      sinceDate?: string;
      untilDate?: string;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiPackAnalyticsSummary> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/analytics/packs/summary`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async listPackFormulaAnalytics(
    packId: number,
    params: {
      sinceDate?: string;
      untilDate?: string;
      scale?: types.PublicApiAnalyticsScale;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiPackFormulaAnalyticsCollection> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/analytics/packs/${packId}/formulas`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async listWorkspaceMembers(
    workspaceId: string,
    params: {
      includedRoles?: string;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiWorkspaceMembersList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/workspaces/${workspaceId}/users`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async changeUserRole(
    workspaceId: string,
    params: {} = {},
    payload: types.PublicApiChangeRole,
  ): Promise<types.PublicApiChangeRoleResult> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/workspaces/${workspaceId}/users/role`, allParams);
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async listWorkspaceRoleActivity(
    workspaceId: string,
    params: {
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiGetWorkspaceRoleActivity> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/workspaces/${workspaceId}/roles`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async listPacks(
    params: {
      accessType?: types.PublicApiPackAccessType;
      sortBy?: types.PublicApiPacksSortBy;
      onlyWorkspaceId?: string;
      excludePublicPacks?: boolean;
      excludeIndividualAcls?: boolean;
      excludeWorkspaceAcls?: boolean;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiPackSummaryList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs`, pageToken ? {pageToken} : rest);
    return this._makeRequest('GET', codaUrl);
  }

  async createPack(
    params: {} = {},
    payload: types.PublicApiCreatePackRequest,
  ): Promise<types.PublicApiCreatePackResponse> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs`, allParams);
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async getPack(packId: number, params: {} = {}): Promise<types.PublicApiPack> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async updatePack(
    packId: number,
    params: {} = {},
    payload: types.PublicApiUpdatePackRequest,
  ): Promise<types.PublicApiPack> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}`, allParams);
    return this._makeRequest('PATCH', codaUrl, JSON.stringify(payload));
  }

  async deletePack(packId: number, params: {} = {}): Promise<types.PublicApiDeletePackResponse> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}`, allParams);
    return this._makeRequest('DELETE', codaUrl);
  }

  async listPackVersions(
    packId: number,
    params: {
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiPackVersionList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/versions`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async getNextPackVersion(
    packId: number,
    params: {} = {},
    payload: types.PublicApiGetNextPackVersionRequest,
  ): Promise<types.PublicApiNextPackVersionInfo> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/nextVersion`, allParams);
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async getPackVersionDiffs(
    packId: number,
    basePackVersion: string,
    targetPackVersion: string,
    params: {} = {},
  ): Promise<types.PublicApiPackVersionDiffs> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/versions/${basePackVersion}/diff/${targetPackVersion}`,
      allParams,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async registerPackVersion(
    packId: number,
    packVersion: string,
    params: {} = {},
    payload: types.PublicApiRegisterPackVersionRequest,
  ): Promise<types.PublicApiPackVersionUploadInfo> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/versions/${packVersion}/register`,
      allParams,
    );
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async packVersionUploadComplete(
    packId: number,
    packVersion: string,
    params: {} = {},
    payload: types.PublicApiCreatePackVersionRequest,
  ): Promise<types.PublicApiCreatePackVersionResponse> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/versions/${packVersion}/uploadComplete`,
      allParams,
    );
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async createPackRelease(
    packId: number,
    params: {} = {},
    payload: types.PublicApiCreatePackReleaseRequest,
  ): Promise<types.PublicApiPackRelease> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/releases`, allParams);
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async listPackReleases(
    packId: number,
    params: {
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiPackReleaseList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/releases`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async setPackOauthConfig(
    packId: number,
    params: {} = {},
    payload: types.PublicApiSetPackOauthConfigRequest,
  ): Promise<types.PublicApiPackOauthConfigMetadata> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/oauthConfig`, allParams);
    return this._makeRequest('PUT', codaUrl, JSON.stringify(payload));
  }

  async getPackOauthConfig(packId: number, params: {} = {}): Promise<types.PublicApiPackOauthConfigMetadata> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/oauthConfig`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async setPackSystemConnection(
    packId: number,
    params: {} = {},
    payload: types.PublicApiSetPackSystemConnectionRequest,
  ): Promise<types.PublicApiPackSystemConnectionMetadata> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/systemConnection`, allParams);
    return this._makeRequest('PUT', codaUrl, JSON.stringify(payload));
  }

  async patchPackSystemConnection(
    packId: number,
    params: {} = {},
    payload: types.PublicApiPatchPackSystemConnectionRequest,
  ): Promise<types.PublicApiPackSystemConnectionMetadata> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/systemConnection`, allParams);
    return this._makeRequest('PATCH', codaUrl, JSON.stringify(payload));
  }

  async getPackSystemConnection(packId: number, params: {} = {}): Promise<types.PublicApiPackSystemConnectionMetadata> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/systemConnection`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async getPackPermissions(packId: number, params: {} = {}): Promise<types.PublicApiPackPermissionList> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/permissions`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async addPackPermission(
    packId: number,
    params: {} = {},
    payload: types.PublicApiAddPackPermissionRequest,
  ): Promise<types.PublicApiAddPackPermissionResponse> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/permissions`, allParams);
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async deletePackPermission(
    packId: number,
    permissionId: string,
    params: {} = {},
  ): Promise<types.PublicApiDeletePackPermissionResponse> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/permissions/${permissionId}`,
      allParams,
    );
    return this._makeRequest('DELETE', codaUrl);
  }

  async listPackMakers(
    packId: number,
    params: {
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiListPackMakersResponse> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/makers`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async addPackMaker(
    packId: number,
    params: {} = {},
    payload: types.PublicApiAddPackMakerRequest,
  ): Promise<types.PublicApiAddPackMakerResponse> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/maker`, allParams);
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async deletePackMaker(
    packId: number,
    loginId: string,
    params: {} = {},
  ): Promise<types.PublicApiAddPackMakerResponse> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/maker/${loginId}`, allParams);
    return this._makeRequest('DELETE', codaUrl);
  }

  async listPackCategories(
    packId: number,
    params: {
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiListPackCategoriesResponse> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/categories`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async addPackCategory(
    packId: number,
    params: {} = {},
    payload: types.PublicApiAddPackCategoryRequest,
  ): Promise<types.PublicApiAddPackCategoryResponse> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/category`, allParams);
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async deletePackCategory(
    packId: number,
    categoryName: string,
    params: {} = {},
  ): Promise<types.PublicApiDeletePackCategoryResponse> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/category/${categoryName}`,
      allParams,
    );
    return this._makeRequest('DELETE', codaUrl);
  }

  async uploadPackAsset(
    packId: number,
    params: {} = {},
    payload: types.PublicApiUploadPackAssetRequest,
  ): Promise<types.PublicApiPackAssetUploadInfo> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/uploadAsset`, allParams);
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async uploadPackSourceCode(
    packId: number,
    params: {} = {},
    payload: types.PublicApiUploadPackSourceCodeRequest,
  ): Promise<types.PublicApiPackSourceCodeUploadInfo> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/uploadSourceCode`, allParams);
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async packAssetUploadComplete(
    packId: number,
    packAssetId: string,
    packAssetType: types.PublicApiPackAssetType,
    params: {} = {},
  ): Promise<types.PublicApiPackAssetUploadCompleteResponse> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/assets/${packAssetId}/assetType/${packAssetType}/uploadComplete`,
      allParams,
    );
    return this._makeRequest('POST', codaUrl);
  }

  async packSourceCodeUploadComplete(
    packId: number,
    packVersion: string,
    params: {} = {},
    payload: types.PublicApiPackSourceCodeUploadCompleteRequest,
  ): Promise<types.PublicApiPackSourceCodeUploadCompleteResponse> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/versions/${packVersion}/sourceCode/uploadComplete`,
      allParams,
    );
    return this._makeRequest('POST', codaUrl, JSON.stringify(payload));
  }

  async getPackSourceCode(
    packId: number,
    packVersion: string,
    params: {} = {},
  ): Promise<types.PublicApiPackSourceCodeInfo> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/versions/${packVersion}/sourceCode`,
      allParams,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async listPackListings(
    params: {
      packAccessTypes?: types.PublicApiPackAccessTypes;
      packIds?: string;
      onlyWorkspaceId?: string;
      excludePublicPacks?: boolean;
      excludeWorkspaceAcls?: boolean;
      excludeIndividualAcls?: boolean;
      orderBy?: types.PublicApiPackListingsSortBy;
      direction?: types.PublicApiSortDirection;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiPackListingList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/listings`, pageToken ? {pageToken} : rest);
    return this._makeRequest('GET', codaUrl);
  }

  async getPackListing(
    packId: number,
    params: {
      workspaceId?: string;
    } = {},
  ): Promise<types.PublicApiPackListingDetail> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/${packId}/listing`, allParams);
    return this._makeRequest('GET', codaUrl);
  }

  async listPackLogs(
    packId: number,
    docId: string,
    params: {
      logTypes?: string;
      beforeTimestamp?: string;
      afterTimestamp?: string;
      order?: string;
      q?: string;
      requestIds?: string;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiPackLogsList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/docs/${docId}/logs`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async listGroupedPackLogs(
    packId: number,
    docId: string,
    params: {
      beforeTimestamp?: string;
      afterTimestamp?: string;
      order?: string;
      q?: string;
      limit?: number;
      pageToken?: string;
    } = {},
  ): Promise<types.PublicApiGroupedPackLogsList> {
    const allParams = {
      ...params,
    };
    const {pageToken, ...rest} = allParams;
    const codaUrl = withQueryParams(
      `${this.protocolAndHost}/apis/v1/packs/${packId}/docs/${docId}/groupedLogs`,
      pageToken ? {pageToken} : rest,
    );
    return this._makeRequest('GET', codaUrl);
  }

  async getPackCount(
    params: {
      isPublished?: boolean;
      accessType?: types.PublicApiPackAccessType;
      excludePublicPacks?: boolean;
    } = {},
  ): Promise<types.PublicApiCountResponse> {
    const allParams = {
      ...params,
    };
    const codaUrl = withQueryParams(`${this.protocolAndHost}/apis/v1/packs/count`, allParams);
    return this._makeRequest('GET', codaUrl);
  }
}
