append_unmatched: true
nav:
  - index.md
  - quickstart.md
  - examples.md
  - features
  - indexing
  - development.md
  - troubleshooting.md
  - Publishing: https://docs.superhuman.com/@hector/go-agent-development-guide/listing-publishing-7
  - upgrade.md
