nav:
  - overview.md
  - design.md
  - blocks
  - basics
  - advanced
  - development
  - Distribution:
    - Sharing & publishing: https://help.coda.io/en/articles/5987280-sharing-and-publishing-a-pack
    - Selling packs: https://help.coda.io/en/articles/6381607-selling-packs-on-coda
  - ...
