name: "Combine Dependabot PRs"
on:
  workflow_dispatch:

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 
      - uses: gita-codaio/batch-dependabot@main
        with:
          branchPrefix: "dependabot"
          mustBeGreen: true 
          combineBranchName: "batch-dependabot"
          baseBranch: "main"
          openPR: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}



